# 主机与超时设置
api:
  # 获取IP地址的服务
  ip_service_url: "https://api.ipify.org?format=json"
  # 根据IP获取地理位置的服务 API (注意 {ip} 是占位符)
  geo_service_url: "http://ip-api.com/json/{ip}"
  # 全局请求超时时间（秒）
  timeout: 20.0

# 查询数据源 (天气搜索引擎)
sources:
  google: "https://www.google.com/search?q={city} weather"
  bing: "https://www.bing.com/search?q={city} weather"
  baidu: "https://www.baidu.com/s?wd={city} 天气"